# Configuration for circle packing constructor evolution (n=26)
max_iterations: 100  # Increased iterations
checkpoint_interval: 10
log_level: "INFO"
# LLM configuration
llm:
  models:
    - name: "gpt-4o-mini"
      api_key: ""
      base_url: ""
      temperature: 0.7
      top_p: 0.95
      max_tokens: 8192
      timeout: 60
      weight: 0.5
      retries: 2
      retry_delay: 3
      random_seed: 42
      use_web: false
      tavily_api_key: ""

  evaluator_models:
    - name: "gpt-4o-mini"
      api_key: ""
      base_url: ""
      temperature: 0.7
      top_p: 0.95
      max_tokens: 8192
      timeout: 60
      weight: 0.5
      retries: 2
      retry_delay: 3
      random_seed: 42
      use_web: false
      tavily_api_key: ""

prompt:
  system_message: |
    You are an expert mathematician specializing in circle packing problems and computational geometry. Your task is to improve a constructor function that directly produces a specific arrangement of 26 circles in a unit square, maximizing the sum of their radii. The AlphaEvolve paper achieved a sum of 2.635 for n=26.

    Key geometric insights:
    - Circle packings often follow hexagonal patterns in the densest regions
    - Maximum density for infinite circle packing is pi/(2*sqrt(3)) ≈ 0.9069
    - Edge effects make square container packing harder than infinite packing
    - Circles can be placed in layers or shells when confined to a square
    - Similar radius circles often form regular patterns, while varied radii allow better space utilization
    - Perfect symmetry may not yield the optimal packing due to edge effects

    Focus on designing an explicit constructor that places each circle in a specific position, rather than an iterative search algorithm.
  num_top_programs: 3
  use_template_stochasticity: true

# Database configuration
island:
  population_size: 60  # Increased population for more diversity
  archive_size: 25
  random_seed: 68 
  num_islands: 4
  elite_selection_ratio: 0.3
  exploitation_ratio: 0.7
  time_of_meeting: 2

# Evaluator configuration
evaluator:
  timeout: 15
  cascade_evaluation: true
  cascade_thresholds: [0.5, 0.75]
  parallel_evaluations: 4
  use_llm_feedback: false

# graph settings
graph:
  parallel_generate: true
  checkpoint_path: ""

controller:
  resume: true 

rag:
  model: "text-embedding-3-small"
  api_key: ""
  base_url: ""
  chunk_size: 1000
  max_retries: 3
  timeout: 30.0
  skip_empty: True
  tiktoken_enabled: True
  allowed_special: ["<|endoftext|>", "<|startoftext|>"]
  disallowed_special: []
  retry_min_seconds: 1
  retry_max_seconds: 60

llm_rag:
  model: "gpt-4o-mini"
  api_key: ""
  base_url: ""
  temperature: 0.7
  top_p: 0.95
  max_tokens: 8192
  timeout: 60

use_rag: true 
rag_doc_path: "openevolve_graph/circle_packing/documents"
vector_save_dir: "openevolve_graph/circle_packing/vector_store"

max_iterations: 500
checkpoint_interval: 20
log_level: "INFO"
log_dir: "openevolve_graph/circle_packing/logs"
diff_based_evolution: ture  # Use full rewrites instead of diffs
allow_full_rewrites: false    # Allow full rewrites for constructor functions
random_seed: 42 
max_code_length: 20000
init_program_path: "openevolve_graph/circle_packing/initial_program.py"
evalutor_file_path: "openevolve_graph/circle_packing/evaluator.py"
meeting_interval: 2
random_meeting: true
checkpoint: "openevolve_graph/circle_packing/checkpoint_106"
